create table comex.conta (
	id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 8) NOT NULL,
  	cliente_id integer not null,
  	valor decimal(10,2) not null,

	constraint pk_conta primary key (id),
	constraint uk_cliente_id unique (cliente_id),
  	constraint fk_conta_cliente	foreign key (cliente_id) references comex.cliente (id)
);
COMMIT;